name: "Analyze"

on:
  pull_request:

jobs:
  Analyze:
    runs-on: self-hosted
    steps:
    # This step checks out a copy of your repository.
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: tonasodji/pull_request_fork_2
        
    - name: info  
      run: |
        git rm .github/workflows/analyze.yml
        echo $GITHUB_REPOSITORY
        echo $GITHUB_EVENT_NAME
        echo $GITHUB_BASE_REF
    - name: Analyze
      run: |
        git clone https://github.com/tonasodji/pvs.git
        cd pvs
        pvs-studio-analyzer trace -- make -j8
        pvs-studio-analyzer analyze -j8 -l PVS-Studio.lic -o PVS-Studio.log
        plog-converter PVS-Studio.log -t sarif -o results.sarif
   

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: pvs/results.sarif
