
name: "Analyze"
on:
  workflow_dispatch:

jobs:
  Analyze:
    runs-on: eclairit
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Analyze
      run: |
        git clone https://github.com/tonasodji/test.git
        # Prepare for build
        test/./prepare.sh
        # Analyze the project
        test/analyze.sh openssh
        
    - name: reports SARIF
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ECLAIR/gh-quality-report.sarif
