name: "Analyze"

on:
  push:
  pull_request:
#github environment variables
env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  Analyze:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: tonasodji/test_pull_request
          ref: main
          
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          #echo "$GITHUB_CONTEXT"
          echo "//test" >> main.c
      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1

      - name: Print git commit data
        run: |
          echo "Get commit info"
          echo " - ${{ env.GIT_COMMIT_SHA }}"
          echo " - ${{ env.GIT_COMMIT_SHORT_SHA }}"
          echo "Get author info"
          echo " - ${{ env.GIT_COMMIT_AUTHOR }}"
          echo " - ${{ env.GIT_COMMIT_AUTHOR_NAME }}"
          echo " - ${{ env.GIT_COMMIT_AUTHOR_EMAIL }}"
          echo "Get committer info"
          echo " - ${{ env.GIT_COMMIT_COMMITTER }}"
          echo " - ${{ env.GIT_COMMIT_COMMITTER_NAME }}"
          echo " - ${{ env.GIT_COMMIT_COMMITTER_EMAIL }}"
          echo "Get message info"
          echo " - ${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}"
          echo " - ${{ env.GIT_COMMIT_MESSAGE_SUBJECT_SANITIZED }}"
          echo " - ${{ env.GIT_COMMIT_MESSAGE_BODY }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.TOK }}
      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1

      - name: Print git commit data
        run: |
          echo "Get commit info"
          echo " - ${{ env.GIT_COMMIT_SHA }}"
          echo " - ${{ env.GIT_COMMIT_SHORT_SHA }}"
          echo "Get author info"
          echo " - ${{ env.GIT_COMMIT_AUTHOR }}"
          echo " - ${{ env.GIT_COMMIT_AUTHOR_NAME }}"
          echo " - ${{ env.GIT_COMMIT_AUTHOR_EMAIL }}"
          echo "Get committer info"
          echo " - ${{ env.GIT_COMMIT_COMMITTER }}"
          echo " - ${{ env.GIT_COMMIT_COMMITTER_NAME }}"
          echo " - ${{ env.GIT_COMMIT_COMMITTER_EMAIL }}"
          echo "Get message info"
          echo " - ${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}"
          echo " - ${{ env.GIT_COMMIT_MESSAGE_SUBJECT_SANITIZED }}"
          echo " - ${{ env.GIT_COMMIT_MESSAGE_BODY }}"
      
      - name: Analyze
        run: |
          git clone https://github.com/tonasodji/pvs.git
          cd pvs
          pvs-studio-analyzer trace -- make -j8
          pvs-studio-analyzer analyze -j8 -l PVS-Studio.lic -o PVS-Studio.log
          plog-converter PVS-Studio.log -t sarif -o results.sarif


      - name: reports SARIF
        run: |
          (gzip -c pvs/results.sarif | base64 -w0) > results
          gh api --method POST -H "Accept: application/vnd.github+json" \
          /repos/$GITHUB_REPOSITORY/code-scanning/sarifs \
          -f commit_sha=$GITHUB_SHA -f ref=$GITHUB_REF -F sarif=@results
