name: "Analyze"

on:
  workflow_call:
  push:

jobs:
  Analyze:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Show GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

      
    - name: Analyze
      run: |
        echo ${{ github.event.pull_request.head.sha }}
        git clone https://github.com/tonasodji/pvs.git
        cd pvs
        pvs-studio-analyzer trace -- make -j8
        pvs-studio-analyzer analyze -j8 -l PVS-Studio.lic -o PVS-Studio.log
        plog-converter PVS-Studio.log -t sarif -o results.sarif
   

    - name: reports SARIF
      run: |
        (gzip -c pvs/results.sarif | base64 -w0) > results
        gh api --method POST -H "Accept: application/vnd.github+json" \
        /repos/$GITHUB_REPOSITORY/code-scanning/sarifs \
        -f commit_sha=$GITHUB_SHA -f ref=$GITHUB_REF -F sarif=@results
