name: "Analyze"
on:
  workflow_dispatch:
  pull_request:
jobs:
  analyze:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: run
        run: |
          git clone https://github.com/tonasodji/pvs.git
          cd pvs
          pvs-studio-analyzer trace -- make -j8
          pvs-studio-analyzer analyze -j8 -l PVS-Studio.lic -o PVS-Studio.log
          plog-converter PVS-Studio.log -t sarif -o results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: pvs/results.sarif

