name: pull_request

on:
  workflow_dispatch:
  push:
env:
    GH_TOKEN: ${{ secrets.TOK }}
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Make changes to pull request
        run: date +%s > report.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: test
          delete-branch: true
          
