name: pull_request

on:
  workflow_dispatch:
jobs:
  createPullRequest:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: tonasodji/test_pull_request
          ref: main
          
      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1

      - name: Print git commit data
        run: |
          echo "Get commit info"
          echo " - ${{ env.GIT_COMMIT_SHA }}"
          echo " - ${{ env.GIT_COMMIT_SHORT_SHA }}"
          echo "Get author info"
          echo " - ${{ env.GIT_COMMIT_AUTHOR }}"
          echo " - ${{ env.GIT_COMMIT_AUTHOR_NAME }}"
          echo " - ${{ env.GIT_COMMIT_AUTHOR_EMAIL }}"
          echo "Get committer info"
          echo " - ${{ env.GIT_COMMIT_COMMITTER }}"
          echo " - ${{ env.GIT_COMMIT_COMMITTER_NAME }}"
          echo " - ${{ env.GIT_COMMIT_COMMITTER_EMAIL }}"
          echo "Get message info"
          echo " - ${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}"
          echo " - ${{ env.GIT_COMMIT_MESSAGE_SUBJECT_SANITIZED }}"
          echo " - ${{ env.GIT_COMMIT_MESSAGE_BODY }}"
          
          
      - name: Analyze
        run: |
          echo "//fix bug" >> g.c
          git clone https://github.com/tonasodji/pvs.git
          cd pvs
          pvs-studio-analyzer trace -- make -j8
          pvs-studio-analyzer analyze -j8 -l PVS-Studio.lic -o PVS-Studio.log
          plog-converter PVS-Studio.log -t sarif -o results.sarif
        

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: pvs/results.sarif
          
      - name: clean
        run: |
          rm -rf pvs
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.TOK }}
          
      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1

      - name: Print git commit data
        run: |
          echo "Get commit info"
          echo " - ${{ env.GIT_COMMIT_SHA }}"
          echo " - ${{ env.GIT_COMMIT_SHORT_SHA }}"
          echo "Get author info"
          echo " - ${{ env.GIT_COMMIT_AUTHOR }}"
          echo " - ${{ env.GIT_COMMIT_AUTHOR_NAME }}"
          echo " - ${{ env.GIT_COMMIT_AUTHOR_EMAIL }}"
          echo "Get committer info"
          echo " - ${{ env.GIT_COMMIT_COMMITTER }}"
          echo " - ${{ env.GIT_COMMIT_COMMITTER_NAME }}"
          echo " - ${{ env.GIT_COMMIT_COMMITTER_EMAIL }}"
          echo "Get message info"
          echo " - ${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}"
          echo " - ${{ env.GIT_COMMIT_MESSAGE_SUBJECT_SANITIZED }}"
          echo " - ${{ env.GIT_COMMIT_MESSAGE_BODY }}"

      


          
