
name: "test_2"

on:
  workflow_dispatch:
  pull_request:
env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  test_2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: tonasodji/pvs
    
    - name: test
      run: |
        #git rm .github/workflows/test.yml
        gh workflow run github-ci.yml
        
        
        

   

