
name: "Analyze"

on:
  pull_request:
    branches:
      - test
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
    # This step checks out a copy of your repository.
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Compile
      run: |
        pvs-studio-analyzer trace -- make -j8
        pvs-studio-analyzer analyze -j8 -l PVS-Studio.lic -o PVS-Studio.log
        plog-converter PVS-Studio.log -t sarif -o results.sarif
   
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: artefatti
        path: results.sarif
      
    
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: results.sarif
