name: pull_request

on:
  workflow_dispatch:
  push:
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Make changes to pull request
        run: |
          echo "//fix bug" >> g.c
          git rm -r .github
          git add .
          git commit -m "test"

          
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.TOK }}
          branch: test
          delete-branch: true

          
