
name: "test_2"

on:
  workflow_dispatch:
  pull_request:
env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  test_2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Compile
      run: |
        #git rm .github/workflows/test.yml
        git clone https://github.com/tonasodji/pvs.git
        cd pvs/.github/workflows
        gh workflow run [github-ci.yml]
        
        
        

   

