
name: "test_2"

on:
  workflow_dispatch:
  pull_request:

env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  test:
    uses: tonasodji/pvs/.github/workflows/github-ci.yml@main
        
        
        

   

