name: pull_request

on:
  workflow_dispatch:
jobs:
  createPullRequest:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: tonasodji/test_pull_request
          ref: main
          
      - name: Analyze
        run: |
          echo "//fix bug" >> g.c
          git clone https://github.com/tonasodji/pvs.git
          cd pvs
          pvs-studio-analyzer trace -- make -j8
          pvs-studio-analyzer analyze -j8 -l PVS-Studio.lic -o PVS-Studio.log
          plog-converter PVS-Studio.log -t sarif -o results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: pvs/results.sarif
      
      - name: clean
        run: |
          rm -rf pvs
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.TOK }}


          
