
name: "test_2"

on:
  workflow_dispatch:
  push:
env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: tonasodji/test_pull_request
          ref: main
      - name: create file
        run: echo "ciao" > ciao
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.1.1
        with:
          token: ${{ secrets.TOK }}
  test_1:
    needs: test
    uses: tonasodji/pvs/.github/workflows/github-ci.yml@main

        

              


        

        
        
        

   

